# Generated by Django 3.2.4 on 2021-12-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=75)),
                ('doc_post', models.CharField(max_length=255)),
                ('doc_timming', models.CharField(max_length=19)),
                ('doc_ranking', models.CharField(max_length=3)),
                ('doc_room', models.IntegerField()),
                ('doc_specialization', models.CharField(max_length=100)),
                ('phone_number', models.PositiveIntegerField()),
                ('doc_email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('doc_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareapp.adddepartment')),
            ],
        ),
        migrations.CreateModel(
            name='AI_Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_operator', models.CharField(max_length=200)),
                ('msg_visitor', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
                ('phone_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('problem', models.CharField(max_length=20)),
                ('time', models.DurationField(max_length=11)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareapp.adddoctors')),
            ],
        ),
        migrations.CreateModel(
            name='MakeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=80)),
                ('Age', models.CharField(max_length=2)),
                ('Disease', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareapp.adddoctors')),
            ],
        ),
    ]
