# Generated by Django 3.2.4 on 2022-01-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0003_auto_20220102_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistereFroms',
            new_name='RegisteredFroms',
        ),
    ]
