# Generated by Django 3.2.4 on 2022-01-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0004_rename_registerefroms_registeredfroms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomsAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym1', models.CharField(max_length=200)),
                ('sym2', models.CharField(max_length=200)),
                ('sym3', models.CharField(max_length=200)),
                ('sym4', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisteredFroms',
        ),
    ]
