# Generated by Django 3.2.4 on 2022-01-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0005_auto_20220102_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=200)),
                ('stuemail', models.EmailField(max_length=200)),
                ('stupass', models.CharField(max_length=200)),
            ],
        ),
    ]
