# Generated by Django 3.2.4 on 2022-01-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0008_auto_20220103_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SymptomsAdd',
        ),
    ]
