# Generated by Django 3.2.4 on 2022-01-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0009_delete_symptomsadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom1', models.CharField(max_length=200)),
                ('symptom2', models.CharField(max_length=200)),
                ('symptom3', models.CharField(max_length=200)),
                ('symptom4', models.CharField(max_length=200)),
            ],
        ),
    ]
