# Generated by Django 3.2.4 on 2022-01-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0011_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SymptomAdd',
        ),
    ]
