# Generated by Django 3.2.4 on 2022-01-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0012_delete_symptomadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskTitle',
            new_name='symt1',
        ),
    ]
