# Generated by Django 3.2.4 on 2022-01-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0013_rename_tasktitle_task_symt1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
