# Generated by Django 3.2.4 on 2022-01-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0015_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='symt1',
            field=models.CharField(max_length=255),
        ),
    ]
