# Generated by Django 3.2.4 on 2022-01-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0016_alter_task_symt1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='symt1',
            new_name='tasktitle',
        ),
    ]
