# Generated by Django 3.2.4 on 2022-01-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0017_rename_symt1_task_tasktitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasktitle',
            new_name='taskTitle',
        ),
    ]
