# Generated by Django 3.2.4 on 2022-01-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0019_auto_20220103_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sig',
        ),
    ]
