# Generated by Django 3.2.4 on 2022-01-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0021_emptinsert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emptinsert',
            old_name='country',
            new_name='symp1',
        ),
        migrations.RenameField(
            model_name='emptinsert',
            old_name='email',
            new_name='symp2',
        ),
        migrations.RenameField(
            model_name='emptinsert',
            old_name='empname',
            new_name='symp3',
        ),
    ]
