# Generated by Django 3.2.4 on 2022-01-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0026_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
