# Generated by Django 3.2.4 on 2022-01-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0028_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='predict',
        ),
    ]
